### ISSUE TITLE
[Feature Request] Add compatibility to KDE Connect

### ISSUE THREAD

**Issue by Mannshoch** [linuxwhatelse/service.linuxwhatelse.notify#1]
Does it work with KDEconnect?

**Comment by tadly** [comment]
Nope, doesn't...
Notify was written back when I haven't even heard of kdeconnect...

**Comment by Mannshoch** [comment]
Add compartibility to [KDE Connect](https://cgit.kde.org/kdeconnect-android.git/about/).
It should be possible:
- add/decline/delete a kdeconnect device
- Get a notification for Phonecalls and Messages
- Play received URL
- show received Audio/Picture/Video
- allow control the current player

Nice Feature but not important.:
- If multiple picture in once received made a Dia show. Otherwise replace the current view.
- Allow to control the cursor and write text with the virtual touchpad function.

**Comment by tadly** [comment]
Sorry, but that's not gonna happen.

Notify is it's own "thing" (not a good one but even so) and adding support for kde-connect is basically the same as writing a new add-on.

This is actually what _should_ happen, a dedicated kde-connect add-on for kodi.

**Comment by Mannshoch** [comment]
That's OK, thank you for your Feedback. I hope someone could be found that will do that.
