### ISSUE TITLE
Cached image files should be written in binary format

### ISSUE THREAD

**Issue by abelgomez** [linuxwhatelse/service.linuxwhatelse.notify#2]
Cached image files are opened with write permissions in text format, rather than in binary format (see https://github.com/linuxwhatelse/service.linuxwhatelse.notify/blob/6654aa3c1d3376e487f9a5d92dad412ce8fe2a88/addon/routes/notification.py#L57). As a consequence, saved PNG files are corrupt and cannot be displayed (at least when running Kodi in Windows).

**Comment by tadly** [comment]
Update for the official repo is requested. Thanks again :)

**Comment by abelgomez** [comment]
Great, thanks!
